services:
  db:
    image: postgres:15
    container_name: inventory-system-db
    environment:
      POSTGRES_DB: inventory-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./inventory-system-api
    container_name: inventory-system-backend
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/inventory-system
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./inventory-system-web
    container_name: inventory-system-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
